version: "3"

networks:
  coursework:

services:
    web:
        image: nginx:alpine
        container_name: coursework-web
        environment:
            TZ: Europe/Kiev
        ports:
            - "83:80"
        restart: always
        volumes:
            - ../src:/var/www/
            - ./nginx/logs:/var/log/nginx
            - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
        networks:
          - coursework

    php:
        build:
            context: php
            dockerfile: Dockerfile
            args:
                - CURRENT_USER=admin
        container_name: coursework-php
        environment:
            TZ: Europe/Kiev
        volumes:
            - ../src:/var/www/
            - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        networks:
          - coursework

    artisan:
        container_name: coursework-artisan
        build:
            context: artisan
            dockerfile: Dockerfile
            args:
                - CURRENT_USER=admin
        environment:
            TZ: Europe/Kiev
        volumes:
            - ../src:/var/www/
        depends_on:
            - mysql
        working_dir: /var/www/
        entrypoint: [ "php", "/var/www/artisan" ]
        networks:
            - coursework

    mysql:
        image: mysql:8.0.33
        container_name: coursework-mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3309:3306"
        volumes:
            - mysql-data:/var/lib/mysql
            - ./mysql/configs/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            TZ: Europe/Kiev
            MYSQL_DATABASE: laravel
            MYSQL_USER: admin
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
          - coursework

volumes:
    mysql-data:
        driver: local

